FROM python:3.9

ARG APP_HOST
ARG APP_PORT
ARG APP_WORKERS
ARG APP_TIMEOUT

ENV ENV_APP_HOST=$APP_HOST
ENV ENV_APP_PORT=$APP_PORT
ENV ENV_APP_WORKERS=$APP_WORKERS
ENV ENV_APP_TIMEOUT=$APP_TIMEOUT

WORKDIR /src
COPY ./Pipfile Pipfile
COPY ./Pipfile.lock Pipfile.lock

RUN pip install pipenv && pipenv install --dev --system

EXPOSE $APP_PORT
CMD uvicorn app.setup:create_app --host 0.0.0.0 --port $APP_PORT --reload --log-config /src/app/log_conf.yml