FROM python:3.9

WORKDIR /src
COPY ./Pipfile Pipfile
COPY ./Pipfile.lock Pipfile.lock

RUN pip install pipenv && pipenv install --dev --system

EXPOSE 8000
CMD uvicorn app.setup:create_app --host localhost --port 8000 --reload --log-config /src/app/log_conf.yml